# Generated by Django 2.0.7 on 2021-12-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_carr_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carr',
            name='User',
            field=models.TextField(default='null'),
        ),
    ]
